# Generated by Django 2.2.19 on 2023-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231102_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='ava1.jpg', upload_to='profile_images'),
        ),
    ]
