# Generated by Django 4.2.2 on 2023-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category_rename_photo_postsphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
