# Generated by Django 2.2.19 on 2023-04-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230413_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
