# Generated by Django 4.2.2 on 2023-12-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_filedownloads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileDownloads',
            new_name='File',
        ),
    ]
