# Generated by Django 4.2.2 on 2023-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_photogallery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
