# Generated by Django 4.2.7 on 2023-12-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
