# Generated by Django 4.2.7 on 2023-12-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_news_options'),
        ('backend', '0004_rename_filedownloads_file'),
    ]

    operations = [
    ]
