# Generated by Django 4.2.2 on 2023-12-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_filedownloads_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='description',
        ),
    ]
