# Generated by Django 4.2.2 on 2023-08-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_photo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['time_update'], 'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
