# Generated by Django 4.2.2 on 2024-01-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_merge_20231211_0005'),
        ('backend', '0005_remove_photogallery_description'),
    ]

    operations = [
    ]
