# Generated by Django 4.2.2 on 2023-08-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_photo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PostsPhoto',
        ),
        migrations.AlterModelOptions(
            name='postsphoto',
            options={'ordering': ['time_create'], 'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
